version: "3"

vars:
  entry: ./cmd/scout/main.go
  bin: scout
  views: ./views/

tasks:
  default:
    deps: [build]

  build:
    silent: true
    cmds:
      - templ generate {{.views}} 
      - go build -o {{.bin}} {{.entry}} 

  clean:
    silent: true
    cmds:
      - rm -r {{.views}}/*_templ.go
      - rm {{.bin}}
